config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :tasks
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  has_one_attached :ref_file # Using inbuilt ActiveStorage module of rails 5.2 for attachments
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates_presence_of :name, :description
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy
  enum priority: [:high, :low, :medium]
  enum status: [:open, :done]
  validates_presence_of :name, :description, :priority, :deadline
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_task

  def create
    @comment = @task.comments.new(comment_params)
    if @comment.save
      flash[:notice] = 'Comment created successfully'
    else
      flash[:error] = 'Comment cannot be created.'
    end
  end

  def destroy
    @comment = @task.comments.find(params[:id])
    if @comment.destroy
      flash[:notice] = "Comment Deleted successfully"
    else
      flash[:error] = "Comment cannot be Deleted - #{@comment.errors.full_messages.join(', ')}"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :ref_file)
  end

  def find_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, except: [:index, :new, :create]

  def index
    @projects = current_user.projects
  end

  def new
    @project = current_user.projects.new()
    render_form
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save(params[:project])
      flash[:notice] = 'Project created successfully'
    else
      flash[:error] = 'Project cannot be created.'
    end
  end

  def edit
    render_form
  end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project updated successfully'
    else
      flash[:error] = 'Project cannot be updated.'
    end
  end

  def show
    @tasks = @project.tasks
  end

  def destroy
    if @project.destroy
      flash[:notice] = "Project #{@project.name} Deleted successfully"
    else
      flash[:error] = "Project cannot be Deleted - #{@project.errors.full_messages.join(', ')}"
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def find_project
    @project = current_user.projects.find(params[:id])
  end

  def render_form
    respond_to do |format|
      format.js { render template: '/projects/form.js.erb' }
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project
  before_action :find_task, except: [:new, :create]

  def new
    @task = @project.tasks.new
    render_form
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:notice] = 'Task created successfully'
    else
      flash[:error] = 'Task cannot be created.'
    end
  end

  def edit
    render_form
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Task updated successfully'
    else
      flash[:error] = 'Task cannot be updated.'
    end
  end

  def show
    @comment = @task.comments.new()
    render template: '/tasks/show', layout: false
  end

  def destroy
    if @task.destroy
      flash[:notice] = "Task #{@task.name} Deleted successfully"
    else
      flash[:error] = "Task cannot be Deleted - #{@task.errors.full_messages.join(', ')}"
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :priority, :deadline, :status)
  end

  def find_project
    @project = current_user.projects.find(params[:project_id])
  end

  def find_task
    @task = @project.tasks.find(params[:id])
  end

  def render_form
    respond_to do |format|
      format.js { render partial: '/tasks/form', layout: false }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_errors
    content_tag :div do
      @project.errors.full_messages.each do |error|
        concat content_tag :li, error
      end
    end
  end
end

app/helpers/task_helper.rb
module TaskHelper
  def task_errors
    content_tag :div do
      @task.errors.full_messages.each do |error|
        concat content_tag :li, error
      end
    end
  end
end

app/views/comments/_table_row.html.erb
<ul class="list-group comment_<%= comment.id %>">
  <li class="list-group-item">
    <p>
      <%= comment.description %>
      <%= link_to 'Delete', comment_path(comment.id, task_id: @task.id), method: :delete, remote: true, class: 'pull-right' %>
    </p>
    <% if comment.ref_file.attached? %>
      <%= link_to comment.ref_file.filename, rails_blob_path(comment.ref_file, disposition: "attachment") %>
    <% end %>
  </li>
</ul>

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  $('.comments_list').append("<%=j render partial: '/comments/table_row', locals: { comment: @comment } %>");
  $('.comment_error .alert-danger').addClass('hidden');
  $('form#new_comment')[0].reset();
<% else %>
  $('.comment_error .alert-danger').html("<p><%= flash[:error] %></p><%= @comment.errors.full_messages.join(',') %>").removeClass('hidden');
<% end %>

app/views/comments/destroy.js.erb
<% if @comment.destroyed? %>
  $('.comments_list .comment_<%= @comment.id %>').remove();
<% end %>
$('.flash_msgs').html('<%=j bootstrap_flash %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ToDoApp" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/public/favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="#">ToDoApp</a>
        <% if current_user.present? %>
          <%= link_to('logout', destroy_user_session_path, method: :delete, class: 'pull-right') %>
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div>
          <div class='flash_msgs'>
            <%= bootstrap_flash %>
          </div>
          <%= yield %>
        </div>
      </div><!--/row-->
      <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
                <h3 class='modal-title'>Modal header</h3>
            </div>
            <div class="modal-body">
              <p>My modal content here…</p>
            </div>
            <div class="modal-footer"></div>
          </div>
        </div>
      </div>


      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, url: (@project.new_record? ? projects_path : project_path(@project)), remote: true do |f| %>
  <div class='form-group'>
    <label>Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label>Description</label>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/projects/_table_record.html.erb
<tr class='project_<%= project.id %>'>
  <td><%= project.name %></td>
  <td><%= project.description %></td>
  <td>
    <%= link_to 'Show', project_path(project.id), remote: true %>
    <%= link_to 'Edit', edit_project_path(project.id), remote: true %>
    <%= link_to 'Delete', project_path(project.id), method: :delete, remote: true %>
  </td>
</tr>

app/views/projects/create.js.erb
<% if @project.persisted? %>
  $('#project_list table tbody').append("<%=j render partial: '/projects/table_record', locals: { project: @project } %>");
  clearViewPane();
  $('.flash_msgs').html('<%=j bootstrap_flash %>');
<% else %>
  $('#errors .alert-danger').html("<p><%= flash[:error] %></p><%= project_errors %>").removeClass('hidden');
<% end %>

app/views/projects/destroy.js.erb
<% if @project.destroyed? %>
  $('#project_list table tbody tr.project_<%= @project.id%>').remove();
<% end %>
clearViewPane();
$('.flash_msgs').html('<%=j bootstrap_flash %>');

app/views/projects/form.js.erb
$('#content_pane').html("<%=j render partial: '/projects/form.html.erb' %>")

app/views/projects/index.html.erb
<div class='row'>
  <%= link_to('Add New Project', new_project_path(user_id: current_user.id), class: 'pull-right btn btn-default', remote: true) %>
</div>
<div class='row'>
  <div class='col-md-6' id= 'project_list'>
    <h2><center>Project List</center></h2>
    <table class='table table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <%= render partial: '/projects/table_record', locals: { project: project } %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='col-md-6' id= 'project_pane'>
    <div id='errors'>
      <div class="alert fade in alert-danger hidden">
      </div>
    </div>
    <div id= 'content_pane'></div>
  </div>
</div>
<hr>
<div class='row task_pane'></div>

app/views/projects/show.html.erb
<h2><center>Project Details</center></h2>
<p><strong>Name: <%= @project.name %></strong></p>
<p><strong>Description: </strong><%= @project.description %></p>
<div class='row'>
  <%= link_to('Add New Task', new_task_path(project_id: @project.id), class: 'pull-right btn btn-default', remote: true , 'data-toggle' =>  "modal", 'data-target' => '#modal-window') %>
</div>
<div class='row'>
  <div id= 'task_list'>
    <table class='table table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Priority</th>
          <th>Deadline</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <%= render partial: '/tasks/table_record', locals: { task: task } %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/show.js.erb
$('#content_pane').html("<%=j render template: '/projects/show.html.erb', layout: false %>")

app/views/projects/update.js.erb
<% if @project.errors.present? %>
  $('#errors .alert-danger').html("<p><%= flash[:error] %></p><%= project_errors %>").removeClass('hidden');
<% else %>
  $('#project_list table tbody tr.project_<%= @project.id %>').replaceWith("<%=j render partial: 'table_record', locals: { project: @project } %>");
  clearViewPane();
  $('.flash_msgs').html('<%=j bootstrap_flash %>');
<% end %>

app/views/tasks/_form.html.erb
<div id='errors' class='col-md-12'>
  <div class="alert fade in alert-danger hidden"></div>
</div>
<h3 id="myModalLabel"><%= @project.name %></h3>
<%= form_for @task, url: (@task.new_record? ? tasks_path(project_id: @project.id) : task_path(@task, project_id: @project.id)), remote: true do |f| %>
  <div class='form-group'>
    <label>Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label>Description</label>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label>Priority</label>
    <%= f.select :priority, options_for_select(Task.priorities.map { |k,v| [k.titlecase, k] }, f.object.priority), class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label>Deadline</label>
    <%= f.text_field :deadline, value: f.object.deadline.try(:strftime, '%d/%m/%Y'), class: 'form-control datepicker' %>
  </div>
  <div class='form-group'>
    <label>Status</label>
      <%= f.select :status, options_for_select(Task.statuses.map { |k,v| [k.titlecase, k] }, f.object.status), class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/tasks/_table_record.html.erb
<tr class='task_<%= task.id %>'>
  <td><%= task.name %></td>
  <td><%= task.description %></td>
  <td><%= task.priority.titlecase %></td>
  <td><%= task.deadline.strftime('%d/%m/%Y') %></td>
  <td><%= task.status.titlecase %></td>
  <td>
    <%= link_to 'Show', 'javascript:void(0)', onclick: 'loadTask(this)', 'data-url': task_path(task.id, project_id: @project.id) %>
    <%= link_to 'Edit', edit_task_path(task.id, project_id: @project.id), remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' %>
    <%= link_to 'Delete', task_path(task.id, project_id: @project.id), method: :delete, remote: true %>
  </td>
</tr>

app/views/tasks/create.js.erb
<% if @task.persisted? %>
  $('#task_list table tbody').append("<%=j render partial: '/tasks/table_record', locals: { task: @task } %>");
  $('#myModal').modal('hide');
  $('.flash_msgs').html('<%=j bootstrap_flash %>');
<% else %>
  $('#myModal #errors .alert-danger').html("<p><%= flash[:error] %></p><%= task_errors %>").removeClass('hidden');
<% end %>

app/views/tasks/destroy.js.erb
<% if @task.destroyed? %>
  $('#task_list table tbody tr.task_<%= @task.id%>').remove();
<% end %>
$('.flash_msgs').html('<%=j bootstrap_flash %>');
$('.task_pane').html('');

app/views/tasks/show.html.erb
<h2><center>Task Details</center></h2>
<p><strong>Name: <%= @task.name %></strong></p>
<p><strong>Description: </strong><%= @task.description %></p>
<div class='row'>
  <div class='col-md-6'>
    <label>Priority:</label>
    <%= @task.priority.titlecase %>
  </div>
  <div class='col-md-6'>
    <label>Deadline:</label>
    <%= @task.deadline.strftime('%d/%m/%Y') %>
  </div>
</div>
<div class='row'>
  <div class='col-md-6'>
    <label>Status:</label>
    <%= @task.status.titlecase %>
  </div>
</div>
<div class='col-md-12'>
  <label>Comments:</label>
  <div class='comments_list'>
    <% @task.comments.each do |comment| %>
      <% if comment.persisted? %>
        <%= render partial: '/comments/table_row', locals: { comment: comment } %>
      <% end %>
    <% end %>
  </div>
  <div class='row comment_error'>
    <div class="alert fade in alert-danger hidden"></div>
  </div>
  <%= form_for @comment, url: comments_path(task_id: @task.id), authenticity_token: true, remote: true do |f| %>
    <div class='form-group'>
      <%= f.text_field :description, class: 'form-control', placeholder: 'Add a Comment' %>
    </div>
    <div class='form-group'>
      <%= f.file_field :ref_file %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  <% end %>
</div>

app/views/tasks/update.js.erb
<% if @task.errors.present? %>
  $('#myModal #errors .alert-danger').html("<p><%= flash[:error] %></p><%= task_errors %>").removeClass('hidden');
<% else %>
  $('#task_list table tbody tr.task_<%= @task.id %>').replaceWith("<%=j render partial: '/tasks/table_record', locals: { task: @task } %>");
  $('#myModal').modal('hide');
  $('.flash_msgs').html('<%=j bootstrap_flash %>');
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>